server:
  port: 8080
spring:
  application:
    name: "auth-microservice"
  devtools:
    add-properties: false
adapters:
  r2dbc:
    host: "localhost"
    port: 13450
    database: "postgres"
    username: "postgres"
    password: "postgres"
    schema: "auth_microservice"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
